### ISSUE TITLE
Cannot ssh into vm

### ISSUE THREAD

**Issue by cybertk** [cybertk/vagrant-box-ubuntu-cn#1]
When `vagrant init` with `ubuntu-cn/trusty64`, then `vagrant up` failed with

```
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
```

**Comment by cybertk** [comment]
As [Vagrant official docs](http://docs.vagrantup.com/v2/boxes/base.html) mentioned, by default, Vagrant expects a "vagrant" user to SSH into the machine as. This user should be setup with the [insecure keypair](https://github.com/mitchellh/vagrant/tree/master/keys) that Vagrant uses as a default to attempt to SSH. Also, even though Vagrant uses key-based authentication by default, it is a general convention to set the password for the "vagrant" user to "vagrant". This lets people login as that user manually if they need to.

After `vagrant up`, vagrant will replace the insecure keypair with a new generated keypair. In case of `ubuntu-cn/trusty64`, we packaged the genereted keypair into box which will prevent vagrant connecting to new provisioned machine.

like

```
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
```
